Traceback (most recent call last):
  File "/home/enrico/UiS/DNN/CHESS/main.py", line 15, in <module>
    wandb.config.update(
TypeError: Config.update() got an unexpected keyword argument 'data'
